# Generated by Django 4.1.3 on 2023-02-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UNIDADE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='CUSTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTA', models.CharField(blank=True, max_length=100)),
                ('VALOR', models.FloatField()),
                ('VENCIMENTO', models.DateField()),
                ('FORMA', models.CharField(choices=[('S', 'SEMANAL'), ('M', 'MENSAL'), ('Q', 'QUINZENAL')], default='M', max_length=1)),
                ('PERIODO', models.IntegerField()),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
            ],
        ),
    ]
