apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true
    allow_origins: ['*']
    library_pattern: "node_modules|bower_components|~"
    exclude_from_grouping: "^/webpack"
    source_mapping:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]
        username: "elastic"
        password: "changeme"
      index_pattern: "apm-*-sourcemap*"
    cache.expiration: 5m

  kibana:
    enabled: true
    host: "http://kibana:5601"  # Certifique-se de usar o nome do serviço
    apm:
      enabled: true

  agent.config:
    enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
