# Generated by Django 4.1.3 on 2023-01-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_orden_longe_remove_orden_perto_orden_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='FORMA_PAG',
            field=models.CharField(choices=[('A', 'PIX'), ('B', 'DINHEIRO'), ('C', 'DEBITO'), ('D', 'CREDITO'), ('E', 'CARNER'), ('F', 'PERMUTA')], max_length=1),
        ),
        migrations.CreateModel(
            name='SUB_SERVICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=500)),
                ('SERVICO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.servico')),
            ],
        ),
    ]
