# Generated by Django 4.1.3 on 2022-12-28 03:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=250)),
                ('LOGRADOURO', models.CharField(max_length=250)),
                ('NUMERO', models.CharField(max_length=10)),
                ('BAIRRO', models.CharField(max_length=200)),
                ('CIDADE', models.CharField(max_length=200)),
                ('TELEFONE', models.CharField(blank=True, max_length=30, null=True)),
                ('CPF', models.CharField(max_length=14)),
                ('DATA_NASCIMENTO', models.DateTimeField(blank=True, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('FOTO', models.ImageField(blank=True, null=True, upload_to='foto_img')),
            ],
        ),
        migrations.CreateModel(
            name='COMISSAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.FloatField(blank=True, null=True)),
                ('VENDAS', models.IntegerField(blank=True, null=True)),
                ('TICKET', models.FloatField(blank=True, null=True)),
                ('COMISSAO', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LONGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LONGE_OD_ESF', models.FloatField(blank=True, null=True)),
                ('LONGE_OD_CIL', models.FloatField(blank=True, null=True)),
                ('LONGE_OD_EIXO', models.FloatField(blank=True, null=True)),
                ('LONGE_OD_DNP', models.FloatField(blank=True, null=True)),
                ('LONGE_OD_AL', models.FloatField(blank=True, null=True)),
                ('LONGE_OD_AD', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_ESF', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_CIL', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_EIXO', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_DNP', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_AL', models.FloatField(blank=True, null=True)),
                ('LONGE_OE_AD', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PERTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERTO_OD_ESF', models.FloatField(blank=True, null=True)),
                ('PERTO_OD_CIL', models.FloatField(blank=True, null=True)),
                ('PERTO_OD_EIXO', models.FloatField(blank=True, null=True)),
                ('PERTO_OD_DNP', models.FloatField(blank=True, null=True)),
                ('PERTO_OD_AL', models.FloatField(blank=True, null=True)),
                ('PERTO_OD_AD', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_ESF', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_CIL', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_EIXO', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_DNP', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_AL', models.FloatField(blank=True, null=True)),
                ('PERTO_OE_AD', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UNIDADE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ORDEM_SERVICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 47, 44, 824835))),
                ('LENTES', models.CharField(max_length=500)),
                ('ARMACAO', models.CharField(max_length=500)),
                ('TRATAMENTO', models.CharField(max_length=500)),
                ('OBSERVACAO', models.TextField(max_length=1000)),
                ('VALOR', models.FloatField()),
                ('FORMA_PAG', models.CharField(choices=[('D', 'DINHEIRO'), ('C', 'CARTAO'), ('A', 'CARNER')], max_length=1)),
                ('ENTRADA', models.FloatField()),
                ('PREVISAO_ENTREGA', models.DateField()),
                ('QUANTIDADE_PARCELA', models.IntegerField()),
                ('ANEXO', models.ImageField(blank=True, null=True, upload_to='anexo_img')),
                ('STATUS', models.CharField(choices=[('A', 'EM ABERTO'), ('E', 'ENCERRADO'), ('C', 'CANCELADO')], default='A', max_length=1)),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.cliente')),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('LONGE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.longe')),
                ('PERTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.perto')),
            ],
        ),
        migrations.CreateModel(
            name='CUSTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTA', models.CharField(blank=True, max_length=100)),
                ('VALOR', models.FloatField()),
                ('VENCIMENTO', models.DateTimeField()),
                ('FORMA', models.CharField(choices=[('S', 'SEMANAL'), ('M', 'MENSAL'), ('Q', 'QUINZENAL')], default='M', max_length=1)),
                ('PERIODO', models.IntegerField()),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE_EXAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidades.cliente')),
                ('LONGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidades.longe')),
                ('PERTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidades.perto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='LONGE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unidades.longe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='PERTO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unidades.perto'),
        ),
    ]
