# Generated by Django 4.1.3 on 2022-12-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMISSAO',
        ),
        migrations.DeleteModel(
            name='ORDEM_SERVICO',
        ),
    ]
