# Generated by Django 4.1.3 on 2022-12-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0003_alter_cliente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='LONGE',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='PERTO',
        ),
        migrations.AddField(
            model_name='cliente',
            name='EXAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Unidades.cliente_exame'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='VENCIMENTO',
            field=models.DateField(),
        ),
    ]
