# Generated by Django 4.1.3 on 2023-01-15 15:41

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidades', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('NOME', models.CharField(blank=True, max_length=100, null=True)),
                ('CPF', models.CharField(blank=True, max_length=18)),
                ('DATA_NASCIMENTO', models.DateField(blank=True, null=True)),
                ('STATUS', models.CharField(choices=[('A', 'Ativo'), ('F', 'Ferias'), ('I', 'Inativo')], default='A', max_length=1)),
                ('FUNCAO', models.CharField(blank=True, choices=[('V', 'Vendedor'), ('C', 'Caixa'), ('G', 'Gerente')], max_length=1, null=True)),
                ('UNIDADE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SALARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.FloatField()),
                ('DISCRIMINAÇAO', models.CharField(blank=True, max_length=200, null=True)),
                ('DATA', models.DateTimeField()),
                ('COLABORADOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateTimeField(default=datetime.date(2023, 1, 15))),
                ('LENTES', models.CharField(max_length=500)),
                ('ARMACAO', models.CharField(max_length=500)),
                ('TRATAMENTO', models.CharField(max_length=500)),
                ('OBSERVACAO', models.TextField(max_length=1000)),
                ('VALOR', models.FloatField()),
                ('FORMA_PAG', models.CharField(choices=[('D', 'DINHEIRO'), ('C', 'CARTAO'), ('A', 'CARNER')], max_length=1)),
                ('ENTRADA', models.FloatField()),
                ('PREVISAO_ENTREGA', models.DateField()),
                ('QUANTIDADE_PARCELA', models.IntegerField()),
                ('ANEXO', models.ImageField(blank=True, null=True, upload_to='anexo_img')),
                ('STATUS', models.CharField(choices=[('A', 'EM ABERTO'), ('E', 'ENCERRADO'), ('C', 'CANCELADO')], default='A', max_length=1)),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.cliente')),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('LONGE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.longe')),
                ('PERTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.perto')),
                ('VENDEDOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COMISSAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.FloatField(blank=True, null=True)),
                ('VENDAS', models.IntegerField(blank=True, null=True)),
                ('TICKET', models.FloatField(blank=True, null=True)),
                ('COMISSAO', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('VENDEDOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
