# Generated by Django 4.1.3 on 2022-12-31 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='DATA',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 13, 22, 23, 526557)),
        ),
    ]
