# Generated by Django 4.1.3 on 2022-12-28 03:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0002_delete_comissao_delete_ordem_servico'),
        ('Autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDEM_SERVICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 53, 29, 965475))),
                ('LENTES', models.CharField(max_length=500)),
                ('ARMACAO', models.CharField(max_length=500)),
                ('TRATAMENTO', models.CharField(max_length=500)),
                ('OBSERVACAO', models.TextField(max_length=1000)),
                ('VALOR', models.FloatField()),
                ('FORMA_PAG', models.CharField(choices=[('D', 'DINHEIRO'), ('C', 'CARTAO'), ('A', 'CARNER')], max_length=1)),
                ('ENTRADA', models.FloatField()),
                ('PREVISAO_ENTREGA', models.DateField()),
                ('QUANTIDADE_PARCELA', models.IntegerField()),
                ('ANEXO', models.ImageField(blank=True, null=True, upload_to='anexo_img')),
                ('STATUS', models.CharField(choices=[('A', 'EM ABERTO'), ('E', 'ENCERRADO'), ('C', 'CANCELADO')], default='A', max_length=1)),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.cliente')),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('LONGE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.longe')),
                ('PERTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.perto')),
                ('VENDEDOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='COMISSAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.FloatField(blank=True, null=True)),
                ('VENDAS', models.IntegerField(blank=True, null=True)),
                ('TICKET', models.FloatField(blank=True, null=True)),
                ('COMISSAO', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('VENDEDOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
