# Generated by Django 4.1.3 on 2022-12-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0002_alter_ordem_servico_data'),
        ('Autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DATA_NASCIMENTO',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='NOME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UNIDADE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade'),
        ),
    ]
