# Generated by Django 4.1.3 on 2022-12-28 04:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades', '0002_delete_comissao_delete_ordem_servico'),
        ('Autenticacao', '0002_ordem_servico_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 1, 1, 25, 885196))),
                ('LENTES', models.CharField(max_length=500)),
                ('ARMACAO', models.CharField(max_length=500)),
                ('TRATAMENTO', models.CharField(max_length=500)),
                ('OBSERVACAO', models.TextField(max_length=1000)),
                ('VALOR', models.FloatField()),
                ('FORMA_PAG', models.CharField(choices=[('D', 'DINHEIRO'), ('C', 'CARTAO'), ('A', 'CARNER')], max_length=1)),
                ('ENTRADA', models.FloatField()),
                ('PREVISAO_ENTREGA', models.DateField()),
                ('QUANTIDADE_PARCELA', models.IntegerField()),
                ('ANEXO', models.ImageField(blank=True, null=True, upload_to='anexo_img')),
                ('STATUS', models.CharField(choices=[('A', 'EM ABERTO'), ('E', 'ENCERRADO'), ('C', 'CANCELADO')], default='A', max_length=1)),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.cliente')),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('LONGE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.longe')),
                ('PERTO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.perto')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DATA_NASCIMENTO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FUNCAO',
            field=models.CharField(blank=True, choices=[('V', 'Vendedor'), ('C', 'Caixa'), ('G', 'Gerente')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='ORDEM_SERVICO',
        ),
        migrations.AddField(
            model_name='orden',
            name='VENDEDOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
