# Generated by Django 4.1.3 on 2022-12-28 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacao', '0003_orden_alter_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='DATA',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 1, 11, 35, 341758)),
        ),
    ]
