# Generated by Django 4.1.3 on 2022-12-29 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacao', '0005_alter_orden_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='DATA',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 10, 38, 7, 264293)),
        ),
    ]
