# Generated by Django 4.1.3 on 2023-02-08 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=250)),
                ('LOGRADOURO', models.CharField(max_length=250)),
                ('NUMERO', models.CharField(max_length=10)),
                ('BAIRRO', models.CharField(max_length=200)),
                ('CIDADE', models.CharField(max_length=200)),
                ('TELEFONE', models.CharField(blank=True, max_length=30, null=True)),
                ('CPF', models.CharField(max_length=14)),
                ('DATA_NASCIMENTO', models.DateField(blank=True, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('FOTO', models.ImageField(blank=True, null=True, upload_to='foto_img')),
                ('DATA_CADASTRO', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(choices=[('A', 'EM ABERTO'), ('E', 'ENCERRADO'), ('C', 'CANCELADO')], default='A', max_length=1)),
                ('ANEXO', models.ImageField(blank=True, null=True, upload_to='anexo_img')),
                ('DATA', models.DateTimeField(default=django.utils.timezone.now)),
                ('PREVISAO_ENTREGA', models.DateField()),
                ('SERVICO', models.CharField(max_length=500)),
                ('SUB_SERVICO', models.CharField(max_length=500)),
                ('RECEITA', models.TextField(blank=True, max_length=2000, null=True)),
                ('LENTES', models.CharField(blank=True, max_length=500, null=True)),
                ('ARMACAO', models.CharField(blank=True, max_length=500, null=True)),
                ('OBSERVACAO', models.TextField(blank=True, max_length=1000, null=True)),
                ('FORMA_PAG', models.CharField(choices=[('A', 'PIX'), ('B', 'DINHEIRO'), ('C', 'DEBITO'), ('D', 'CREDITO'), ('E', 'CARNER'), ('F', 'PERMUTA')], max_length=1)),
                ('VALOR', models.FloatField()),
                ('QUANTIDADE_PARCELA', models.IntegerField()),
                ('ENTRADA', models.FloatField()),
                ('DARA_ENCERRAMENTO', models.DateTimeField(blank=True, null=True)),
                ('CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.cliente')),
                ('FILIAL', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Unidades.unidade')),
                ('VENDEDOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
