# Generated by Django 4.1.3 on 2023-02-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='DARA_ENCERRAMENTO',
            new_name='DATA_ENCERRAMENTO',
        ),
    ]
